### ISSUE TITLE
Style docs to match Figma layout

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#27]
- [x] Sidebar style
- [x] Typography
- [x] Contributors avatar stack (see #32)
- [x] Recommended reading functionality (link to the proper article) (see #33, closed in #50)
- [x] External articles (see #50)
